DROP TABLE IF EXISTS coffee_house;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS coffee_beans;
DROP TABLE IF EXISTS coffee_drink;
DROP TABLE IF EXISTS coffee_maker;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS supplier;

