title: Java Documentation
description: Comprehensive Java documentation and examples
baseurl: "/java"
url: "https://natandaniel.github.io"

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
