title: Java Learning Repository
description: Comprehensive Java documentation and examples
baseurl: "/java" # the subpath of your site, e.g. /blog
url: "https://natandaniel.github.io" # the base hostname & protocol for your site

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
