title: Java Documentation
description: Comprehensive Java documentation and examples
baseurl: "/java"
url: "https://natandaniel.github.io"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme


